added monitor function

diff --git a/bin/pfmonitor b/bin/pfmonitor
--- a/bin/pfmonitor
+++ b/bin/pfmonitor
@@ -30,6 +30,16 @@ trap cleanup EXIT
 
 #set -o xtrace
 
+display_help()
+{
+    echo "Usage: $(basename $0) [OPTION]"
+    echo "options:"
+    echo "  -t, --time      the simulation start time to monitor"
+    echo "  -s, --supplement <filepath>"
+    echo "                  location of a supplemental gnuplot script to include in monitors"
+    echo "  -h, --help      print usage"
+}
+
 startTime=0
 
 #parse arguments
@@ -59,6 +69,14 @@ case "$1" in
             fi
         done
         ;;
+    -h|--help)
+        display_help
+        exit 0
+        ;;
+    -*|--*)
+        echo "Invalid option $1"
+        display_help
+        exit 1
 esac
 done
 
